### ISSUE TITLE
Bugs: Hide-and-Seek

### ISSUE THREAD

**Issue by hassanShakur** [batoolfatima2135/Portfolio#12]
There are 3 issues I found in your code specifically in the `form-validation.js` and they are as below:

1. When adding event listeners to forms, you should use the `submit` event and not the `click` event.
2. You should use the `getElementById()` in place of `getElementByClass()` when selecting the email input on line 4.
3. I noticed a wrong `id` selector when trying to select the `error-div`. Change the id from `errordiv` to `error-div`.

Other than that, awesome work ✅

**Comment by batoolfatima2135** [comment]
hey @hassanShakur ! Thank you so much for pointing out the errors.
<img src="https://media2.giphy.com/media/BYoRqTmcgzHcL9TCy1/giphy.gif"/>
I have gone through them and have resolved them.
Keep supporting 👍
