### ISSUE TITLE
Review peer to peer

### ISSUE THREAD

**Issue by Kal2403** [batoolfatima2135/Portfolio#4]
1. Contact Form need to be center.
2. Added hover to Buttons.

**Comment by batoolfatima2135** [comment]
**Hey!**

<img src="https://media1.giphy.com/media/sNJrIBqpcgIacLn5mO/giphy.gif"/>

**Thanks** for your input. 👍  I have implemented your suggestions 💯 
**Keep supporting!**

**Comment by batoolfatima2135** [comment]
**Hey!**

<img src="https://media1.giphy.com/media/sNJrIBqpcgIacLn5mO/giphy.gif"/>

**Thanks** for your input. 👍  I have implemented your suggestions 💯 
**Keep supporting!**
